---
title: "p8105_hw5_rc3520"
author: "Ruyi Chen"
date: "2023-11-14"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggplot2)
library(dplyr)
library(broom)
```
#Problem 1
```{r}
homicide = 
  read_csv("data/homicide-data.csv") |>
  janitor::clean_names()|>
  mutate(city_state = paste(city, state, sep = ","))
view(homicide)
```


```{r}
homicide_city_state =
  homicide |>
  group_by(city_state, disposition) |>
  count(disposition) |>
  pivot_wider(
    names_from = disposition,
    values_from = n
  ) |>
  janitor::clean_names()|>
  mutate_all(~coalesce(., 0))|>
  mutate(total_homicide = closed_without_arrest + open_no_arrest + closed_by_arrest,
    unsolved_homicide = closed_without_arrest + open_no_arrest)
homicide_city_state
```

```{r}
baltimore_homicide =
  homicide_city_state |>
  filter(city_state == "Baltimore,MD")
baltimore_homicide

prop_test_result =
  prop.test(
  x = baltimore_homicide$unsolved_homicide,
  n = baltimore_homicide$total_homicide
  ) |>
  broom::tidy() 

prop_test_result |>
  knitr::kable()
```
##The proportion of homicides that are unsolved in Baltimore is around 64.55607% (CI: 62.75625%, 66.31599%).

```{r}
prop_test = function (city_name) {
    prop.test(
  x = homicide_city_state$unsolved_homicide[homicide_city_state$city_state == city_name ],
  n = homicide_city_state$total_homicide[homicide_city_state$city_state == city_name ]
  ) |>
    broom::tidy()}

purrr::map_df(pull(homicide_city_state, city_state), prop_test)
```

```{r}
city = data.frame(city_state = homicide_city_state$city_state)
prob_test_city_state = purrr::map_df(pull(homicide_city_state, city_state), prop_test)
prob_city_state = bind_cols(city, prob_test_city_state) 

prob_city_state = arrange(prob_city_state, estimate)

view(prob_city_state)

ggplot(prob_city_state, aes(x = city_state, y = estimate)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), width = 0.1) +
  theme(axis.text.x = element_text(angle = 60, hjust = 1))
```

#Problem 2

```{r}
file_paths=tibble(
  files_name=list.files(path="data/zip-data", pattern = "*.csv",full.names = TRUE))  |> 
  mutate(data=map(files_name,read.csv)) 
zip_final =
  file_paths |>
  unnest(everything()) |>
  mutate(
    id = as.numeric(gsub("\\D", "", files_name)),
    arm = substr(files_name, start = 15, stop = 17)
  )|>
  select(files_name,id, arm, everything())|>
  pivot_longer(
    cols=starts_with("week"),
    names_to = "week",
    values_to ="obs"
  )|>
mutate(week = as.numeric(gsub("\\D", "", week)))
view(zip_final)
```

##Make a spaghetti plot showing observations on each subject over time, and comment on differences between groups
```{r}
ggplot(zip_final,aes(x = week, y = obs, color = files_name),data_df) +
  geom_line()+
  facet_wrap(.~arm)+
  labs(
    title="Observations over 8 weeks by Subject",
    x="Week",
    y="Observation",
    color = "Subject"
    )
```

#Problem 3
#set the design elements and generate 5000 datasets from the model
```{r}
pvalue_estimate_sim = function(mu, n = 30,sigma = 5) {
  data_simulation = tibble(x = rnorm(n = 30, mean = mu, sd = sigma)) |>
    t.test() |>  
    broom::tidy() |>  
    select(estimate, p.value)
  }

expand_grid(population_mean = 0, time = 1:5000) |> 
  mutate(result_df = map(population_mean, pvalue_estimate_sim)) |> 
  unnest(result_df)
```




