p8105_hw5_rc3520
================
Ruyi Chen
2023-11-14

\#Problem 1

``` r
homicide = 
  read_csv("data/homicide-data.csv") |>
  janitor::clean_names()|>
  mutate(city_state = paste(city, state, sep = ","))
```

    ## Rows: 52179 Columns: 12
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (9): uid, victim_last, victim_first, victim_race, victim_age, victim_sex...
    ## dbl (3): reported_date, lat, lon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
view(homicide)
```

``` r
homicide_city_state =
  homicide |>
  group_by(city_state, disposition) |>
  count(disposition) |>
  pivot_wider(
    names_from = disposition,
    values_from = n
  ) |>
  janitor::clean_names()|>
  mutate_all(~coalesce(., 0))|>
  mutate(total_homicide = closed_without_arrest + open_no_arrest + closed_by_arrest,
    unsolved_homicide = closed_without_arrest + open_no_arrest)
```

    ## `mutate_all()` ignored the following grouping variables:
    ## • Column `city_state`
    ## ℹ Use `mutate_at(df, vars(-group_cols()), myoperation)` to silence the message.

``` r
homicide_city_state
```

    ## # A tibble: 51 × 6
    ## # Groups:   city_state [51]
    ##    city_state     closed_by_arrest closed_without_arrest open_no_arrest
    ##    <chr>                     <dbl>                 <dbl>          <dbl>
    ##  1 Albuquerque,NM              232                    52             94
    ##  2 Atlanta,GA                  600                    58            315
    ##  3 Baltimore,MD               1002                   152           1673
    ##  4 Baton Rouge,LA              228                    16            180
    ##  5 Birmingham,AL               453                    64            283
    ##  6 Boston,MA                   304                     0            310
    ##  7 Buffalo,NY                  202                     8            311
    ##  8 Charlotte,NC                481                    44            162
    ##  9 Chicago,IL                 1462                   387           3686
    ## 10 Cincinnati,OH               385                    49            260
    ## # ℹ 41 more rows
    ## # ℹ 2 more variables: total_homicide <dbl>, unsolved_homicide <dbl>

``` r
baltimore_homicide =
  homicide_city_state |>
  filter(city_state == "Baltimore,MD")
baltimore_homicide
```

    ## # A tibble: 1 × 6
    ## # Groups:   city_state [1]
    ##   city_state   closed_by_arrest closed_without_arrest open_no_arrest
    ##   <chr>                   <dbl>                 <dbl>          <dbl>
    ## 1 Baltimore,MD             1002                   152           1673
    ## # ℹ 2 more variables: total_homicide <dbl>, unsolved_homicide <dbl>

``` r
prop_test_result =
  prop.test(
  x = baltimore_homicide$unsolved_homicide,
  n = baltimore_homicide$total_homicide
  ) |>
  broom::tidy() 

prop_test_result |>
  knitr::kable()
```

|  estimate | statistic | p.value | parameter |  conf.low | conf.high | method                                               | alternative |
|----------:|----------:|--------:|----------:|----------:|----------:|:-----------------------------------------------------|:------------|
| 0.6455607 |   239.011 |       0 |         1 | 0.6275625 | 0.6631599 | 1-sample proportions test with continuity correction | two.sided   |

\##The proportion of homicides that are unsolved in Baltimore is around
64.55607% (CI: 62.75625%, 66.31599%).
